import{a as v,S as b,i}from"./assets/vendor-DqB7j7Ix.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&l(d)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const w="51422130-3e4e47cfb8dd90f1485b7732f",R="https://pixabay.com/api/";async function m(r,o){const e=new URLSearchParams({key:w,q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",page:o,per_page:15});return(await v.get(`${R}?${e}`)).data}const h=document.querySelector(".gallery"),y=document.querySelector(".load-more"),c=document.querySelector(".loader"),S=new b(".gallery a");function g(r){const o=r.map(e=>`
      <li>
        <a class="gallery-item" href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
          <div class="info">
            <div><span>❤️</span> ${e.likes}</div>
            <div><span>👁️</span> ${e.views}</div>
            <div><span>💬</span> ${e.comments}</div>
            <div><span>💾</span> ${e.downloads}</div>
          </div>
        </a>
      </li>
    `).join("");h.insertAdjacentHTML("beforeend",o),S.refresh()}function $(){h.innerHTML=""}function L(){c.classList.remove("hidden"),c.classList.add("visible")}function f(){c.classList.add("hidden"),c.classList.remove("visible")}function q(){y.classList.remove("hidden")}function p(){y.classList.add("hidden")}let u="",n=1,a=0;const B=document.querySelector("#search-form"),M=document.querySelector(".load-more");B.addEventListener("submit",async r=>{r.preventDefault();const o=r.target.elements.searchQuery.value.trim();if(!o){i.warning({message:"Будь ласка, введіть пошуковий запит!",position:"topRight"});return}u=o,n=1,$(),p();try{L();const e=await m(u,n);if(a=e.totalHits,e.hits.length===0){i.info({message:"Вибач, друже, але за вашим запитом зображень не знайдено. Спробуйте інший запит!",position:"topRight"});return}i.success({message:`Ура! Ми знайшли ${a} зображень.`,position:"topRight"}),g(e.hits),a>15&&q()}catch{i.error({message:"Щось пішло не так. Спробуйте ще раз пізніше.",position:"topRight"})}finally{f()}});M.addEventListener("click",async()=>{n+=1;try{L();const r=await m(u,n);g(r.hits),P();const o=Math.ceil(a/15);n>=o&&(p(),i.info({message:"Вибачте, але ви досягли кінця результатів пошуку.",position:"topRight"}))}catch{i.error({message:"Не вдалося завантажити більше зображень. Спробуйте ще раз.",position:"topRight"})}finally{f()}});function P(){const r=document.querySelector(".gallery li");if(r){const{height:o}=r.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}}p();f();
//# sourceMappingURL=index.js.map
